# Generated by Django 3.1 on 2022-07-31 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=150)),
                ('class_description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_class_code_enabled', models.BooleanField(default=True)),
                ('class_code', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'classroom_students',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='classroom.classroom')),
            ],
            options={
                'verbose_name_plural': 'ratings',
            },
        ),
    ]
