# Generated by Django 3.1 on 2022-09-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220901_1456'),
        ('classroom', '0002_auto_20220731_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomstudents',
            name='classroom_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classoom_related', to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomstudents',
            name='enrolled_student_id',
            field=models.ManyToManyField(blank=True, related_name='classroom_students', to='users.Student'),
        ),
    ]
