# Generated by Django 3.1 on 2022-09-01 09:11

import attendance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220901_1456'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancevideomodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancevideomodel',
            name='video',
            field=models.FileField(upload_to=attendance.models.attendance_video_path),
        ),
    ]
