# Generated by Django 3.1 on 2022-09-16 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0005_auto_20220910_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancevideomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_video_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
