# Generated by Django 3.1 on 2022-08-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='student',
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.user'),
            preserve_default=False,
        ),
    ]
