# Generated by Django 3.1 on 2022-08-21 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220821_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.attendence_pic_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_for_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
