# Generated by Django 3.1 on 2022-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220828_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervideo',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
