# Generated by Django 3.1 on 2022-09-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220901_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
